"""Initial migration with users, tasks, conversations, and messages tables

Revision ID: eb96631ac141
Revises: 
Create Date: 2026-01-14 18:27:01.304069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb96631ac141'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique conversation identifier (auto-increment)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner of the conversation (foreign key to users)',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment=None,
               existing_comment='When conversation started (UTC)',
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment=None,
               existing_comment='Last message timestamp (UTC, auto-updated)',
               existing_nullable=False)
    op.drop_index('idx_conversations_created_at', table_name='conversations')
    op.drop_index('idx_conversations_user_id', table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'conversations',
        existing_comment='Chat sessions between users and AI assistant (Phase III)',
        schema=None
    )
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique message identifier (auto-increment)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Parent conversation (foreign key to conversations)',
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Message owner for security/auditing (foreign key to users)',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Message sender - "user" or "assistant"',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(length=5000),
               comment=None,
               existing_comment='Message text (max 5000 characters)',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment=None,
               existing_comment='When message was sent (UTC)',
               existing_nullable=False)
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_index('idx_messages_user_id', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'messages',
        existing_comment='Individual messages within conversations (Phase III)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'messages',
        'Individual messages within conversations (Phase III)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('idx_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='When message was sent (UTC)',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(length=5000),
               comment='Message text (max 5000 characters)',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Message sender - "user" or "assistant"',
               existing_nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.UUID(),
               comment='Message owner for security/auditing (foreign key to users)',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='Parent conversation (foreign key to conversations)',
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique message identifier (auto-increment)',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'conversations',
        'Chat sessions between users and AI assistant (Phase III)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index('idx_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('idx_conversations_created_at', 'conversations', [sa.text('created_at DESC')], unique=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='Last message timestamp (UTC, auto-updated)',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='When conversation started (UTC)',
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner of the conversation (foreign key to users)',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique conversation identifier (auto-increment)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    # ### end Alembic commands ###
